### ISSUE TITLE
Icons responsiveness

### ISSUE THREAD

**Issue by diego-rapoport** [opensource-force/site#11]
So I was thinking that the responsiveness of the icons ate the bottom were not very good. So I made some changes and it seems better now. I also removed one `div` from the HTML.
Please give feedback on this and if you guys think that's a valid change.

**Comment by diego-rapoport** [comment]
I already linked the branch I worked on in this issue.

**Comment by ackledotdev** [comment]
That's great that you've helped out! 

We can't see your changes though, would you mind opening a pull request?

**Comment by ackledotdev** [comment]
oh my bad, just found it.
